### ISSUE TITLE
[Question] Get Sale Id from Payment

### ISSUE THREAD

**Issue by lucasbasquerotto** [paypal/PayPal-PHP-SDK#1115]
After getting the payment data from PayPal, in every case I saw, people just use `transactions[0]` and `related_resources[0]` to get the sale id, like the code bellow:

```
$transactions = $payment->getTransactions();
$related_resources = $transactions[0]->getRelatedResources();
$sale = $related_resources[0]->getSale();
$sale_id = $sale->getId();
```

Both the `transactions` and `related_resources` fields are arrays.

Is that safe?

Can there be more than 1 transaction and more than 1 related resource in a way that will (possibly) cause inconsistencies?

**Comment by trainerbill** [comment]
There will always be at least one transaction and one related_resources so it is safe.

**Comment by feltkamptv** [comment]
> There will always be at least one transaction and one related_resources so it is safe.

False. There is not always one related_resources. I currently have the issue where a Sale was completed, I have a paymentId, but I cannot get the transactionId from the payment because there are no related resources for this payment. We are currently processing 500+ payments per day and some completed payments do not have any related resources with the transactions.

```
$payment = Payment::get($paymentId, $apiContext);
$transactions = $payment->getTransactions();
$transaction_id = $transactions[0]->getRelatedResources()[0]->getSale()->getId(); // This fails in some cases
$total_related = count($transactions[0]->getRelatedResources()); // returns 0 in some cases
```

So hopefully somebody has a different solution?

**Comment by wzulfikar** [comment]
Hi @feltkamptv, any update on the intermittent empty `related_resources`?

**Comment by wzulfikar** [comment]
Hi @feltkamptv, any update on the intermittent empty `related_resources`? I'm curious to what you mark transactions which have no `related_resources`. Did you mark it as "success" (money received by your system), "pending", or "failed"?
