### ISSUE TITLE
NO SUPPORT (Dead Project)??

### ISSUE THREAD

**Issue by jonjie0317** [paypal/PayPal-PHP-SDK#1187]
Is this package still alive?

**Comment by daslicht** [comment]
I like to know that at all, The while Paypal support is kind of broken, we dont even get answers in teh official Support forum.

**Comment by Neokyuubi** [comment]
@daslicht I'm thinking the same thing ! and by the way i will try switch to the classic API, i heard that it's more trusted than the REST API.

**Comment by daslicht** [comment]
The ReST AP works here so far. 
By Classic do you mean the NVP/SOAP APIs ?:
https://developer.paypal.com/docs/classic/api/#express-checkout 
?
It says : 
Important: This integration method is Deprecated as of January 1, 2017. For new integrations,

**Comment by daslicht** [comment]
@jonjie0317 The best PayPal Support I have found is here : 
https://www.paypal-techsupport.com/app/utils/login_form?p_next_page=ask

They answer , sometimes quite fast :)

**Comment by jonjie0317** [comment]
Thanks @daslicht 😄

**Comment by Neokyuubi** [comment]
Thanks @daslicht but you know the REST API has not been updated for too long now and still have missing parts, like this one is a huge deal : [https://github.com/paypal/PayPal-PHP-SDK/issues/956](https://github.com/paypal/PayPal-PHP-SDK/issues/956) and [https://github.com/paypal/PayPal-REST-API-issues/issues/92](https://github.com/paypal/PayPal-REST-API-issues/issues/92) instead you need to do extra work and guess to have it work with different situations.
They say Deprecated but it's still working and a lot of system are built on top of it so i don't think that this is gonna go easily.
I wanna switch to the Classic API because i'm assuming that all the unfinished things that are here in the REST API are finished in the Classic's one, so i need to do some research about this.

And as you said i saw that they called it NVP/SOAP APIs in the dashboard.

**Comment by daslicht** [comment]
just found : https://gitter.im/paypal/paypal-checkout

**Comment by daslicht** [comment]
the PHP sdk is an active project but they are moving to version 2, which is currently in beta. https://github.com/paypal/PayPal-PHP-SDK/tree/2.0-beta

**Comment by prakash-gangadharan** [comment]
Hi @jonjie0317, PHP sdk is an active project.

**Comment by manian-kumaran** [comment]
Is the whole PayPal no longer maintained?

**Comment by prakash-gangadharan** [comment]
@manian-kumaran are you looking for new integration?

**Comment by manian-kumaran** [comment]
It says that NVP/SOAP is deprecated on 1 Jan 2017. 
The new Paypal Checkout does not support third party permission:
https://developer.paypal.com/docs/archive/permissions-service/

The paypal rest 
https://developer.paypal.com/docs/api/rest-sdks/
points to github and they don't have much activity.

How do we use the third party permission 
https://developer.paypal.com/docs/archive/permissions-service/
for Paypal latest checkout:
https://developer.paypal.com/docs/checkout/
