### ISSUE TITLE
max_fail_attempts confusion

### ISSUE THREAD

**Issue by dominhtri1995** [paypal/PayPal-PHP-SDK#1255]
Hi,

I have a few questions about this params.

Let's say I set max_fail_attempts to 4.
1. What does it mean exactly? Does paypal retry to charge the user 4 time during that 1 month period ? Or 4 month of failed payment ?

Right now I have 1 user which Paypal (after a few weeks of failed attempt) email me that "The automatic payment from XYZ has failed 1 times"

2. The XYZ profile is still active right now. How do I make it automatically cancel the profile after 4 failed attempt in 1 month ?  ( I don't want to let him use our service for free in 4 months)

**Comment by prakash-gangadharan** [comment]
Hi @dominhtri1995,
As detailed in https://github.com/paypal/PayPal-REST-API-issues/issues/34 and https://github.com/paypal/PayPal-PHP-SDK/issues/557, for the Billing Plans `max_fail_attempts` parameter here are some clarifications that may help you.


1. What kind of fail attempts? Is that about setup fee or regular payment?
	- It is only for subsequent payments, not for setup fee failure.
2. What happens after failed attempt? Is subscription still Active?
	- Example max_fail_attempts : 2
	For the 1st failed payment attempt subscription will still Active, and next retry will happen after 5 days.
	For the 2nd failed payment attempt subscription will automatically suspended by the system.
3. What happens if merchant have '1' for this param?
	- If `max_fail_attempts` is 1 and if number of failed payment attempt become 1,then the profile will automatically suspended by the system.
4. How merchant can cancel/suspend subscription after failed attempt?
	- Yes merchant can cancel or suspend profile only if failed attempts are less then max_failed_attempt
	There is workaround for this. You have to update your max_failed_attempt to a higher value and then you can cancel the profile.
	https://developer.paypal.com/docs/api/payments.billing-agreements#billing-agreements_cancel
	POST v1/payments/billing-agreements/{agreement_id}/cancel
	https://developer.paypal.com/docs/api/payments.billing-agreements#billing-agreements_suspend
	POST v1/payments/billing-agreements/{agreement_id}/suspend
5. Is there an IPN message after failed attempt?
	- https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECRecurringPayments/#maximum-number-of-failed-payments
	PayPal sends you an IPN message to merchant when the number of failed payments reaches the maximum number specified.
	we will be sending IPN for failed payments to merchant.
6. Can merchant change this param for existing agreements?
	- yes merchant can update maxFailedPayment attempts.

Let us know if it needs any clarifications?

Thanks!
