### ISSUE TITLE
Error in calling billing paln API 

### ISSUE THREAD

**Issue by Aasif001** [paypal/PayPal-PHP-SDK#1283]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

I am having issue in calling billing plan api paypal v1 REST API
https://prnt.sc/oiwmvh

**Comment by Sebi94nbg** [comment]
You got a HTTP status code 403 from the PayPal API server.

From the documentation:
> The request was understood, but the server is not willing to fulfill it. The server can explain the reason for its unwillingness in the response body.

Source: https://developer.paypal.com/docs/classic/ipn/integration-guide/HTMLStatusCodes/

Since you didn't provide any source code, you need to double check your code and make sure, that everything is there, what is required and you also need to make sure, that you're authenticated (correct API credentials).

It's hard to support you here with only a screenshot of the error message, which is not even high resolution - it's hard to read anything from the screenshot since I can not zoom in.

**Comment by Aasif001** [comment]
Please check this [](https://stackoverflow.com/questions/57214207/got-http-response-code-403-when-accessing-https-api-sandbox-paypal-com-v1-paym
)

I have asked the question on stack overflow and also provided the source code.
Please let me know how can i fix this error. 
And if it is permission  issue the let me know how can i opt this permission ?

Thanks.

**Comment by Sebi94nbg** [comment]
Your class `PaypalPaymentController` is building a constructor, which reads information for PayPal from a config file: `$paypal_conf = \Config::get('paypal'); `

How does this file look like?

My code looks like this: `config/payment-methods.php`
```php
return [

    'supportedPaymentMethods' => [
        'paypal' => [
                'name' => 'PayPal',
                'enabled' => env('PAYMENT_METHODS_PAYPAL_ENABLED', true),
                'client_id' => env('PAYMENT_METHODS_PAYPAL_CLIENT_ID'),
                'secret' => env('PAYMENT_METHODS_PAYPAL_SECRET'),
                'webhook_id' => env('PAYMENT_METHODS_PAYPAL_WEBHOOK_ID'),
            ],
    ],
```
`app/Http/Controllers/Helpers/Payments/PayPalController.php`
```php
class PayPalController extends Controller
{
    /*
     * Protected, global variable for API connection.
     */
    protected $apiContext;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        // Provide login information
        $this->apiContext = new \PayPal\Rest\ApiContext(
                            new \PayPal\Auth\OAuthTokenCredential(
                                config('payment-methods.supportedPaymentMethods.paypal.client_id'),
                                config('payment-methods.supportedPaymentMethods.paypal.secret')
                            ));
        
        if(config('app.use_sandbox')) {
            $this->apiContext->setConfig(
                array(
                    'mode' => 'sandbox',
                    'log.LogEnabled' => true,
                    'log.FileName' => storage_path().'/logs/paypal.log',
                    'log.LogLevel' => 'DEBUG'
                )
            );
        } else {
            $this->apiContext->setConfig(
                array(
                    'mode' => 'live',
                    'log.LogEnabled' => true,
                    'log.FileName' => storage_path().'/logs/paypal.log',
                    'log.LogLevel' => 'WARN'
                )
            );
        }
    }
}
```

The PayPal API should return some more information than only "403 error". You should see some text like "invalid amount" or "missing attribute x" or something. Can you see that somewhere?

Since I am currently working on a subscriptions (billing plan) integration as well, I can test your code and provide you my code later as soon as I've finished it.

**Comment by Aasif001** [comment]
<?php 
return [ 
    'client_id' => env('PAYPAL_CLIENT_ID',''),
    'secret' => env('PAYPAL_SECRET',''),
    'settings' => array(
        'mode' => env('PAYPAL_MODE','LIVE'),
        'http.ConnectionTimeOut' => 30,
        'log.LogEnabled' => true,
        'log.FileName' => storage_path() . '/logs/paypal.log',
        'log.LogLevel' => 'ERROR'
    ),
];

**Comment by Aasif001** [comment]
i can show you the entire object info. 
Let me show you.
PayPal\Rest\ApiContext Object
(
    [requestId:PayPal\Rest\ApiContext:private] => 
    [credential:PayPal\Rest\ApiContext:private] => PayPal\Auth\OAuthTokenCredential Object
        (
            [clientId:PayPal\Auth\OAuthTokenCredential:private] => AT5asGGggvG35Q5zmS-kcSt9nmQT_mijXTfShf1LQicvdGXZQsU3d2o6Vg7d2QXiLlb2gdSaDmlzZNQN
            [clientSecret:PayPal\Auth\OAuthTokenCredential:private] => EAA0DZ3iqXsY8v33SLcubFC3IDGLupq3e_21rI62eyh83Id2qrmjl4ON95z5EmeM057FWXQ3g39CVhm9
            [accessToken:PayPal\Auth\OAuthTokenCredential:private] => 
            [tokenExpiresIn:PayPal\Auth\OAuthTokenCredential:private] => 
            [tokenCreateTime:PayPal\Auth\OAuthTokenCredential:private] => 
            [cipher:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Security\Cipher Object
                (
                    [secretKey:PayPal\Security\Cipher:private] => EAA0DZ3iqXsY8v33SLcubFC3IDGLupq3e_21rI62eyh83Id2qrmjl4ON95z5EmeM057FWXQ3g39CVhm9
                )

            [_propMap:PayPal\Common\PayPalModel:private] => Array
                (
                )

        )

)
PayPal\Api\Plan Object
(
    [_propMap:PayPal\Common\PayPalModel:private] => Array
        (
            [name] => Silver Plan
            [description] => Taskenator silver plan 
            [type] => INFINITE
            [payment_definitions] => Array
                (
                    [0] => PayPal\Api\PaymentDefinition Object
                        (
                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                (
                                    [name] => Taskenator Plan Payment
                                    [type] => REGULAR
                                    [frequency] => MONTH
                                    [frequency_interval] => 1
                                    [cycles] => 0
                                    [amount] => PayPal\Api\Currency Object
                                        (
                                            [_propMap:PayPal\Common\PayPalModel:private] => Array
                                                (
                                                    [value] => 10
                                                    [currency] => USD
                                                )

                                        )

                                )

                        )

                )

            [merchant_preferences] => PayPal\Api\MerchantPreferences Object
                (
                    [_propMap:PayPal\Common\PayPalModel:private] => Array
                        (
                            [return_url] => https://www.testtaskenator.com/subscription/true
                            [cancel_url] => https://www.testtaskenator.com/subscription/false
                            [auto_bill_amount] => yes
                            [initial_fail_amount_action] => CONTINUE
                            [max_fail_attempts] => 0
                            [setup_fee] => PayPal\Api\Currency Object
                                (
                                    [_propMap:PayPal\Common\PayPalModel:private] => Array
                                        (
                                            [value] => 0
                                            [currency] => USD
                                        )

                                )

                        )

                )

        )

)

**Comment by Aasif001** [comment]
And thank you very much for your support @Sebi94nbg  :)

**Comment by Sebi94nbg** [comment]
I also get the HTTP status code 403, when I try to create or list subscriptions. All other payment actions within my application are working fine and as expected, so the authentication should be fine since the same is used for all API requests...

This SDK here is using the following URL: `https://api.sandbox.paypal.com/v1/payments/billing-plans/?page_size=1&status=1&page=1&total_required=1`

Using this URL, I get this error message from the PayPal server:
```
{
	"name": "REQUIRED_SCOPE_MISSING",
	"message": "Access token does not have required scope",
	"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#REQUIRED_SCOPE_MISSING",
	"debug_id": "a4559a08e266b"
}
```

PayPal developers reports this API call in this case:
![image](https://user-images.githubusercontent.com/5154682/62413052-171a3600-b60b-11e9-9d9b-23b7802506fe.png)

In the [documentation](https://developer.paypal.com/docs/subscriptions/full-integration/plan-management/#list-plans) is a different URL mentioned: `https://api.sandbox.paypal.com/v1/billing/plans?page_size=2&page=1&total_required=true`

When I update the SDK to use this URL instead, I get a different error:
```
{
	"name": "NOT_AUTHORIZED",
	"message": "Authorization failed due to insufficient permissions.",
	"debug_id": "9b480fa585858",
	"details": [{
		"issue": "PERMISSION_DENIED",
		"description": "You do not have permission to access or perform operations on this resource."
	}],
	"links": [{
		"href": "https://developer.paypal.com/docs/api/v1/billing/subscriptions#NOT_AUTHORIZED",
		"rel": "information_link",
		"method": "GET"
	}]
}
```

...and the much more interesting fact is, that the developer portal is reporting a debug ID, which I didn't got with the previous used URL, which is used by this SDK:
![image](https://user-images.githubusercontent.com/5154682/62413072-8e4fca00-b60b-11e9-8328-c767563e7926.png)

After some research, I found this topic: https://stackoverflow.com/questions/42407477/paypal-payments-rest-api-required-scope-missing

So, I've searched this option and I enabled this one here:

1. Login to https://developer.paypal.com/
2. Open / Go to https://developer.paypal.com/developer/applications/
3. Open your REST API app on the developer portal
4. Scroll down to "SANDBOX APP SETTINGS" (or "LIVE APP SETTINGS")
5. Click on "Advanced Options" next to "Accept payments"
6. Enable "Billing agreements"
7. Click on "Save" at the bottom

![image](https://user-images.githubusercontent.com/5154682/62413108-349bcf80-b60c-11e9-9d85-cfcd8da29dbc.png)

I am not sure, if enabling this options takes some time or if it's the wrong one, but for me didn't change anything. I still receive the same error messages.

I'll contact the technical PayPal support now since I'm already despairing.

**Comment by Sebi94nbg** [comment]
@Aasif001 ok, enabling the above app setting `Billing agreements` should do the job as PayPal stated.

If you still receive the 403 status code, do the same like me: Contact the PayPal support and tell them, that you have enabled this option, but you're still getting this 403 error: https://www.paypal-support.com/ => "Contact Us"

They told me, that it was NOT enabled although I could see, that it was enabled. However: They enabled it again and this solved the issue for me. :)

**Comment by Sebi94nbg** [comment]
Might be helpful as well: #1290

**Comment by prakash-gangadharan** [comment]
@Aasif001, We hope @Sebi94nbg comments resolved your queries, if you still facing any challenges please revert us back.
