### ISSUE TITLE
How to let buyer to confirm payment on paypal?

### ISSUE THREAD

**Issue by danny-36** [paypal/PayPal-PHP-SDK#1288]
I have integrate php paypal sdk on my website and user can go to paypal for payment but after login to paypal and choise your payment method he clik next button and return to my site in the url specified in setReturnUrl where I execute payment but I would like to let the user click a button "pay now" where he still on paypal. 
It's possibile? thanks.

### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by Sebi94nbg** [comment]
The confirmation of the payment usually happens on the PayPal site, where the user logs in, selects a payment method (eg. PayPal balance, credit card, bank, ...) and at least the user confirms the payment.

After the confirmation of the payment, he gets redirected back to your application, where you display a text like "thanks for approving the payment, we will process it in the next few minutes".

PayPal will send you a webhook event, where the payment says "approved" and then you can charge your customer. There is no need to let the user confirm the payment on your site again. That would be just confusing, because he already confirmed it at PayPal.

**Comment by danny-36** [comment]
In my case I have "pay now" button under list of payment methods when I'm logged to paypal sandbox with test account, but in other examples I see a "next" button under list of payment methods when click page change and see "pay now" button. Why this difference?

**Comment by prakash-gangadharan** [comment]
Hi @danny-36, still its confusing do you have any video to demonstrate this issue?

**Comment by prakash-gangadharan** [comment]
@danny-36 , below is the screen shot of sample paypal checkout review page. When buyer click continue button the payment was approved by the buyer.

![image](https://user-images.githubusercontent.com/13796434/66921259-6a185c80-f042-11e9-86b4-ad2264c2084e.png)

**Comment by prakash-gangadharan** [comment]
@danny-36, please revert back if you still having the issue.
