### ISSUE TITLE
Got Http response code 403 when accessing https://api.sandbox.paypal.com/v1/payments/payment/

### ISSUE THREAD

**Issue by aizaz-shahid** [paypal/PayPal-PHP-SDK#1314]
### General information

* SDK/Library version: 1.14.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: [debug_id] => f9a469bdca76c
* Language, language version, and OS: Laravel, Ubuntu18

**Comment by prakash-gangadharan** [comment]
Hi @aizaz-shahid , can you help us with `PayPal-Debug-ID` for this issue?
Refer [Exception Handling](https://github.com/paypal/PayPal-PHP-SDK/wiki/exception-%27PayPal%5CException%5CPayPalConnectionException%27-with-message-%27Got-Http-response-code-400-when-accessing) to understand your error.

**Comment by aizaz-shahid** [comment]
I have updated the details with debug id

**Comment by prakash-gangadharan** [comment]
@aizaz-shahid, Payment is created using the client-id : AZDxjDScFpQ*** Masked ***
f9a469bdca76c -> Payment is executed using the different client-id : AV0bnsJWAnNINmlEK7GT *** Masked ***

Since the client-Ids are different, i.e payment is created using one and executed through another client-id hence the below error is thrown

```json
{
  "entity": {
    "name": "PERMISSION_DENIED",
    "message": "No permission for the requested operation",
    "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id": "f9a469bdca76c"
  },
  "status": 403
}
```
