### ISSUE TITLE
is Agreement Transactions source missing ?

### ISSUE THREAD

**Issue by udokmeci** [paypal/PayPal-PHP-SDK#219]
Hi,

I have checked the source to get transactions of an agreement. According to source the function is defined as 
``` php
   /**
     * List transactions for a billing agreement by passing the ID of the agreement, as well as the start and end dates of the range of transactions to list, to the request URI.
     *
     * @param string $agreementId
     * @param ApiContext $apiContext is the APIContext for this call. It can be used to pass dynamic configuration and credentials.
     * @param PayPalRestCall $restCall is the Rest Call Service that is used to make rest calls
     * @return AgreementTransactions
     */
\PayPal\Api\Agreement::transactions($agreementId, $apiContext = null, $restCall = null)
```
According to response below and comment on function I have to pass some date. However there is no variable I can pass. Is source missing or I'm missing something.

``` json
{
    "name": "VALIDATION_ERROR",
    "details": [
        {
            "field": "start_date",
            "issue": "Valid Query param is start_date."
        },
        {
            "field": "end_date",
            "issue": "Valid Query param is end_date."
        }
    ],
    "message": "Invalid request - see details",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR",
    "debug_id": "6c4832c9bc14e"
}
```

**Comment by jaypatel512** [comment]
Hey @udokmeci It definitely seems like a bug. I think we missed that params as an optional parameters. Let me quickly setup this code, and get back to you. Sorry about the confusion.

**Comment by jaypatel512** [comment]
Hey @udokmeci ! Just [updated the SDK](https://github.com/paypal/PayPal-PHP-SDK/commit/4326394447b946885e654eb46b569cf1bfa2ac63) to include a way to enter params to the request. Can you please have a look at this instead.

https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/Agreement.php#L624

I had to deprecate the `transactions` method, and create a new `createTransaction` because of semVer policy. Also, I have attached the [sample source](http://htmlpreview.github.io/?https://raw.githubusercontent.com/paypal/PayPal-PHP-SDK/master/sample/doc/billing/SearchBillingTransactions.html) too demonstrating on how to achieve that.

I will be making the release soon. However, in the mean time, feel free to either use dev-master or make this change manually on the file, and you will get the latest code, as soon as it is released. Feel free to re-open the issue if you run into another issue.

**Comment by udokmeci** [comment]
Thank you Jay. I will try right away.

**Comment by udokmeci** [comment]
Hi,
Maybe this is also the problem for #221, the first transaction is not an actual transaction. It is only the agreement it self.
``` json
{
    "agreement_transaction_list": [
        {
            "transaction_id": "I-NH33XCX21G93",
            "status": "Created",
            "transaction_type": "Recurring Payment",
            "payer_email": "",
            "payer_name": "Test Buyer",
            "time_stamp": "2015-01-21T09:33:24Z",
            "time_zone": "GMT"
        },
        {
            "transaction_id": "69553069XY3604244",
            "status": "Completed",
            "transaction_type": "Recurring Payment",
            "amount": {
                "currency": "EUR",
                "value": "199.00"
            },
            "fee_amount": {
                "currency": "EUR",
                "value": "-7.12"
            },
            "net_amount": {
                "currency": "EUR",
                "value": "191.88"
            },
            "payer_email": "info-buyer@xxxx.com",
            "payer_name": "Test Buyer",
            "time_stamp": "2015-01-21T09:33:40Z",
            "time_zone": "GMT"
        }
    ]
}
```

Is it a problem or is it how it works? Thank you.

**Comment by jaypatel512** [comment]
No, this is how it is expected when searching for transactions. Each agreement_transaction_list would have first field as the created agreement, and then the rest of them.

**Comment by udokmeci** [comment]
Ok thank you.
