### ISSUE TITLE
#219 gives Warning

### ISSUE THREAD

**Issue by udokmeci** [paypal/PayPal-PHP-SDK#221]
Hi there,
I had opened issue #219. When I was trying to use the feature and It works flawlessly however in logs I have seen this warning message. So here we are.  
```
PayPal\Validation\ModelAccessorValidator: WARNING: Missing Accessor: PayPal\Api\AgreementTransaction:setTimeStamp. Please let us know by creating an issue at https://github.com/paypal/PayPal-PHP-SDK/issues
```
I have also mentioned before `marking`/`adding metadata`/`custom attribute` to payments? Is there any developments about subject. I have checked some other issues and this feature seems to be wanted commonly.

Thank you.

**Comment by jziaja** [comment]
Thanks for reporting this @udokmeci !  It looks like the service is returning the `time_stamp` property instead of the expected `time_updated` property (publicly documented [here](https://developer.paypal.com/docs/api/#agreementtransaction-object), but confusingly the [sample response for the agreement transaction search](https://developer.paypal.com/docs/api/#search-for-transactions) shows the `time_stamp` property).  I'm following up with the API team to get an explanation on this discrepancy as it appears all the SDKs are expecting a `time_updated` property.

As for your request about adding custom information to payments, you're more than welcome to ask that in a new issue or ping us in a previously opened issue for an update.

**Comment by udokmeci** [comment]
Glad to help and It does not seem to be a problem for using SDK.

**Comment by jaypatel512** [comment]
Hey @udokmeci ! Just made the fix to agreementTransactions object. Feel free to either use the current master by mentioning it as "dev-master" in your composer file, or you could wait for the next release. I should be making a new release soon, however we have 1 or 2 tasks to complete before making that release.
