### ISSUE TITLE
Poodle SSL 3.0 Vulnerability

### ISSUE THREAD

**Issue by bilgeoz** [paypal/PayPal-PHP-SDK#227]
Because of the Poodle vulnerability, PayPal has disabled SSLv3.

**Comment by jaypatel512** [comment]
Hey @bilgeoz ! The Fixes to Poodle Attack has been released since [v0.14.2](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v0.14.2). 

We have also released [v1.1.0](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v1.1.0) which has more features and bug fixes. Please update your SDK if you have not done so already, and you should be able to make calls to PayPal APIs.

**Comment by bilgeoz** [comment]
ok, thanks so much.

**Comment by jaypatel512** [comment]
Let me know if you still run into any issues, and we could re-open this bug, and figure it out.
