### ISSUE TITLE
Create Agreement - notify_url

### ISSUE THREAD

**Issue by MartyIX** [paypal/PayPal-PHP-SDK#236]
Hello,

I'm a little confused. There is `$agreement->override_merchant_preferences->notify_url` property (https://developer.paypal.com/docs/api/#create-an-agreement) and the docs says "Notify URL on agreement creation. 1000 characters max. Assigned in response." about it. (https://developer.paypal.com/docs/api/#merchantpreferences-object). It does not make sense to me. The name suggests that I should be able to change `notify_url` but as I tried it it is not possible:

    PayPal\Core\PayPalHttpConnection: FINE: Response : {"name":"VALIDATION_ERROR","details":[{"field":"override_merchant_preferences.notify_url","issue":"Not valid to specify this field in a request"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR","debug_id":"09adfc539c779"}

Is this a bug or a feature?

Thanks!

**Comment by jaypatel512** [comment]
Hey @MartyIX ! I agree. Notify URL, by the naming convention should be a url that you can add in request, that should receive some kind of notification when agreement gets created on this. 

I will ask the documentation team, as well as the subscription team about this, and get back to you as soon as possible. Thanks for your patience.

**Comment by jaypatel512** [comment]
Hey @MartyIX ! I got a response from Subscription team. Currently, notify_url is not supported, but it is reserved for webhook integration that is coming soon. Webhook integration feature will be supported shortly, and then, we would be able to set the notify_url as you would have expected. 

However, currently, we have disabled it to be sent along with the request, and thus the documentation confusion. We will update the docs accordingly. 

Thanks.

**Comment by zeurois** [comment]
Hello

I'm trying to set notify_url in create billing plan but I'm getting error code 400. Is this because it's disabled? In the docs, it says I can set it in merchant_preferences ....

Other than that, I'm not receiving ANY notifications from sandbox environment. I have no idea if first payment of an agreement went through or not. 

The docs are really confusing ....

Thanks!

**Comment by jaypatel512** [comment]
As mentioned earlier, the notify_url field is not currently supported. We are working on adding webhook integration, that will allow us to use that field.

**Comment by zeurois** [comment]
Awesome. Assuming you don't have an exact date, can you recommend a workaround to have monthly subscriptions & notifications working?

**Comment by wjlight** [comment]
hi~ @jaypatel512  currently, the notify_url is not supported ? I'm get error code 400

**Comment by consigliere23** [comment]
Can anyone give us update about this? Seems that the issue is not resolved yet and still no update in docs.

**Comment by thanhphan9787** [comment]
Hello

I'm trying to set notify_url in create billing plan but I'm getting error code 400. Is this because it's disabled? In the docs, it says I can set it in merchant_preferences ....
$merchantPreferences = new MerchantPreferences();
$merchantPreferences->->setNotifyUrl(' My url return')
..........
-----------------------------------------------------------------
=> This error ERROR: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-plans/. {"name":"VALIDATION_ERROR","details":[{"field":"merchant_preferences.notify_url","issue":"Field is invalid in a request."}],"message":"Invalid request. See details.","information_link":"https://developer.paypal.com/docs/api/payments.billing-plans#errors","debug_id":"a0e8b5cf60d6a"}

If not use setNotifyUrl
---Error------

Other than that, I'm not receiving ANY notifications from sandbox environment. I have no idea if first payment of an agreement went through or not.

The docs are really confusing ....

Thanks!

**Comment by razorsharpshady** [comment]
> 400{"name":"VALIDATION_ERROR","details":[{"field":"merchant_preferences.notify_url","issue":"Field is invalid in a request."}],"message":"Invalid request. See details.","information_link":"https://developer.paypal.com/docs/api/payments.billing-plans#errors","debug_id":"67b976e2ae04"}

1) When I try to fetch the old created agreement or plan I get **NotifyUrl is not a fully qualified URL**
2) If I try to create a new billing plan without sending **NotifyUrl**  it says NotifyUrl is not a fully qualified URL
3) When I add NotifyUrl and try to create the plan it says "name":"VALIDATION_ERROR","details":[{"field":"merchant_preferences.notify_url","issue":"Field is invalid in a request."}],

People on stackoverflow says that paypal recently (1-2 days) back changed the responses in their api which is causing the error on php sdks
https://stackoverflow.com/questions/51424433/paypal-php-sdk-notifyurl-is-not-a-fully-qualified-url-error/51431104 

Please get it fixed asap

**Comment by harshadakhire** [comment]
facing some issue.

**Comment by razorsharpshady** [comment]
@harshadakhire 
https://github.com/paypal/PayPal-PHP-SDK/issues/1157 
do what @srjlewis mentioned, 
I faced the problem in plan apis, thanks to lewis now it is solved.
