### ISSUE TITLE
Always getting status code 400 on sample codes.

### ISSUE THREAD

**Issue by genesantos** [paypal/PayPal-PHP-SDK#239]
I'm always getting status code 400 when running sample codes, particulary on making payments

```
        RESPONSE:
ERROR:Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment.{
    "name": "UNKNOWN_ERROR",
    "message": "An unknown error has occurred",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR",
    "debug_id": "239d328c9fc26"
}
```

i'm getting this error for days, got no luck on making actual payment on a terminal, any help
would be appreciated.

Thanks.

**Comment by jziaja** [comment]
Hi @genesantos, are you experiencing this behavior using the default credentials included with the samples?  Is this happening with every sample or just specific ones?  Is the behavior consistent with the samples that are failing?

**Comment by genesantos** [comment]
*are you experiencing this behavior using the default credentials included with the samples?*
  >I'm using my own sandbox crendentials

 *Is this happening with every sample or just specific ones?*
 >these are samples i noticed that is constanly failing:
 * sample\payments\AuthorizePayment.php
 * sample\payments\CreatePayment.php

*Is the behavior consistent with the samples that are failing?*
>yeah, the behavior seems to persist everytime.

 some of samples seems to work like sample\payments\GetAuthorization only when I comment line 9
and replace `$authorizationId` with a real ones dumped from paypal msdk (iOS)

**Comment by jziaja** [comment]
Looking at the logs for that `debug_id`, it looks like the culprit might be with the CC number that is being used (or overused in this case).  Try generating a new CC number for testing and use that with the samples.  This can be quickly done by doing the following:

* Open up your Developer Dashboard and go to your [Sandbox Accounts](https://developer.paypal.com/webapps/developer/applications/accounts) page
* Click **Create Account**
* Fill out the required info and leave the payment method as credit card
* Once created, selec that account in the list and click **Profile** to view the account details
* Click the **Funding** tab on the small window that appears, and you'll see the new credit card number that was generated for you

Let me know how this works out for you.  We've been getting a lot of reports lately that the default cards available with the samples have been causing errors on sandbox due to their overuse.  However, most of the time it's been generating 500 errors and not 400 errors.

**Comment by mattkaye** [comment]
Took me a few hours to find this link. I was having the exact same issue. Changing the Credit Card info now allows me to run transactions on the sandbox. 

There should really be a note about this in the SDK somewhere. It would save a lot of time and headache.

**Comment by jaypatel512** [comment]
Hey @mattkaye ! I agree. We saw many issues opened up recently on Create Payment with Credit Card, and we are thinking of making it obvious for someone to help. I will probably add a message or something in the sample output, mentioning about the work around, if you get a 500 exception. That may help everyone fix things faster I guess. 

Sorry for the confusion though.
