### ISSUE TITLE
"Payments::all" should recieve the complete PaymentHistory

### ISSUE THREAD

**Issue by chrischaan** [paypal/PayPal-PHP-SDK#244]
The "Payment::all" call recieves only payments made with an api call. It looks like it's not possible to get the complete PaymentHistory with the RESTApi, but only with the deprecated MerchantApi. Maybe there should be an option "paymentsource: {all,api,ui}" or something like that.

**Comment by jziaja** [comment]
Unfortunately, this is by design for the APIs.  Payments made using Classic calls are not currently retrievable via REST calls.  I'll forward your feedback to the Payments team, but I don't believe there are plans to add REST support for this any time soon. :(

**Comment by chrischaan** [comment]
So you suggest to get all payments via the Merchant API (TransactionSearch)? But there is also   a notice: "This Classic SDK is not actively supported and will be deprecated in the future. For full support on new integrations, please use the PHP Rest SDK"

**Comment by jziaja** [comment]
If you're working with an existing integration that has been making payment calls to the Classic API using the Merchant SDK, and you'd like to continue getting the history of those payments, then yes, you should continue to use the Merchant SDK.

That message is more intended as a heads up that the Merchant SDK will eventually be deprecated and isn't being actively supported by our team (bug fixes are an exception to this, of course).  However, it will only be deprecated once the REST API has achieved feature parity with the Classic API.  For your case, it doesn't make sense to move to REST just yet since you still need a feature only available in Classic.

**Comment by chrischaan** [comment]
Thank you for the information. Still this point I'm starting to to build the paypal integration so there is no big codebase. 
The last 2 questions:
How long will the Classik/Merchant API get support at minimum?
If you don't plan to support this feature, how will you get parity to the APIs ;)

**Comment by jziaja** [comment]
> How long will the Classik/Merchant API get support at minimum?

The SDK/API will be supported until the REST API has achieved feature parity (or until PayPal decides otherwise).  There's no set date yet, and given that the REST API is still pretty young compared to Classic, it likely won't be happening for quite a while.  However, to help provide guidance for newer integrations, PayPal wanted to include a blanket message on all the Classic SDKs that begins the process of giving developers a 'heads up' with ample time to prepare.

> If you don't plan to support this feature, how will you get parity to the APIs ;)

Technically, the Classic `TransactionSearch` is supported by the REST API - just **only** for payments made via REST calls. :)  So in that respect, it does achieve feature parity, even though the resulting set from the feature may not be identical.  That's where this falls under a design decision by the Payments team.  I believe the reasoning for this is it allows them at any point to break away from using Express Checkout under the hood without needing drastic changes at the API level.

Also, you're not the first one to ask for this, and it's why I'd like to forward your feedback to the Payments team.  If enough people continue to voice their desire to include Classic EC payments in the REST search results, then they may consider adding that support.

**Comment by chrischaan** [comment]
Thanks bro.

**Comment by nepda** [comment]
>  If enough people continue to voice their desire to include Classic EC payments in the REST search results, then they may consider adding that support.

That would be great!
+1

**Comment by intexx** [comment]
I'm casting my vote for the ability to search for and locate ANY transaction via the REST API (and the .NET SDK), not just those created by an API.

In other words, the REST API (and the .NET SDK) should be able to locate transactions that were created manually via the website user interface. A returned list of merely API-created transactions (any API) is simply not sufficient—manually-created transactions should be included as well.

This is a very serious issue. I haven't seen discussion regarding the problem that's dated newer than over a year ago, so I hope attention to it hasn't waned.

Thanks,
Jeff Bowman
Fairbanks, Alaska
