### ISSUE TITLE
ModelAccessorValidator Missing Accessor PayPal\Api\Capture:setTransactionFee

### ISSUE THREAD

**Issue by dabio** [paypal/PayPal-PHP-SDK#254]
```
[26-02-2015 09:30:05] PayPal\Validation\ModelAccessorValidator: WARNING	: Missing Accessor: PayPal\Api\Capture:setTransactionFee. Please let us know by creating an issue at https://github.com/paypal/PayPal-PHP-SDK/issues
```

I've updated to the latest SDK 1.2.1 to get rid of errors. Now those appear in my log. Any ideas?

**Comment by jziaja** [comment]
Hi @dabio , are you seeing this on live or sandbox?  

Also, see [this thread on the Ruby SDK](https://github.com/paypal/PayPal-Ruby-SDK/issues/14#issuecomment-75602853) regarding why it's taking a bit for our SDKs to be updated with the support.

(Also related: Issue #255)

**Comment by dabio** [comment]
@jziaja,

I got the same error as described in #255 with version 0.14.2. I've updated to 1.1.2 and the error disappeared, but now I am having the warning mentioned above for the sandbox.

I cannot access the live logs currently but I'll let you know if I get the warning there as well.

**Comment by jziaja** [comment]
I was able to reproduce this on sandbox as well (which is great because up until yesterday we weren't seeing the newer fields on sandbox).  We'll work to get the support added and push out a new release once we have everything properly tested.  There's a handful of other new features, including support for providing FMF details for REST payments, and we want to make sure everything's working as expected. :)

Also, just so you and others are aware, the public documentation is also in the process of being updated and will soon be updated with this and the other new fields as well.

**Comment by jaypatel512** [comment]
Hey @dabio ! I am working on adding new fields that got introduced in newer release for Payments API. I will let you know when they are released. In the mean time, you should still be able to access/use SDK to make payments. The missing accessors wont let you access the new fields, but older fields would be accessible just fine.

**Comment by jaypatel512** [comment]
Hello @dabio ! I just wanted to update you all on the newer release. I have just completed the [release](https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v1.3.0) that includes Payment API Updates that covers all the new additional fields that Payment API introduced. You should be able to quickly update your setup to this version to get rid of all those missing accessors issue.

Please checkout the release at https://github.com/paypal/PayPal-PHP-SDK/releases/tag/v1.3.0
