### ISSUE TITLE
Does created payment expires?

### ISSUE THREAD

**Issue by jethdeguzman** [paypal/PayPal-PHP-SDK#261]
I've created a payment sale but doesn't execute it for a day. Then when i tried to execute it, I got paypal connection error. I've also tried to look up using payment lookup by payment Id, I got paypal connection error also. Does created payment expires when not executed?

**Comment by jaypatel512** [comment]
Hey @jethdeguzman ! Thats an interesting question. Actually, there was no direct document that pointed it out, but I got a response back from the Payment team, and they mentioned that the payment lifecycle is of approximately 3 hours.

I have not personally tested it myself, but I will do so today. If for some reason, I find anything otherwise, I will re-open this issue.

Thanks.
