### ISSUE TITLE
Fail in test class HyperSchemaTest with circular dependency

### ISSUE THREAD

**Issue by josecelano** [paypal/PayPal-PHP-SDK#288]
It seems there is an assert not passing in test [PayPal\Test\Api\HyperSchemaTest::testSerializationDeserialization](https://github.com/paypal/PayPal-PHP-SDK/blob/46f7e668cd61e465e56382196331e924c584d065/tests/PayPal/Test/Api/HyperSchemaTest.php#L42)

The sample json (for HyperSchema):
````json
{
  "fragmentResolution": "TestSample",
  "readonly": true,
  "contentEncoding": "TestSample",
  "pathStart": "TestSample",
  "mediaType": "TestSample"
}
````
does not contains and array on Links (HyperSchema::links)

By the way, it seems that there is a circular dependency, HyperSchema contains an array of Links and each Links object contains two HyperSchema properties. Probably that's the reason why array of Links was not included in the json.

**Comment by jaypatel512** [comment]
Your suggestion is true. We had this circular dependency, and because few unit tests are auto-created, this test has link checks. However, the test should not fail. We do run unit tests for every commit, and they are passing. Let me know if that is not the case for you. I think it could be something specific to PHP Version causing that. Let me know.

P.S.: Even if json string does not have links, asserting two empty objects still should be true.

I will close the issue now, but feel completely free to re-open if your test are failing.
