### ISSUE TITLE
SSL connect error (sdk version v1.3.0)

### ISSUE THREAD

**Issue by judychu** [paypal/PayPal-PHP-SDK#289]
My e-shop just had a big promotion and many client do payment within a short period of time. I found many of them (not all, about 1/3 are success) failed to reach the Paypal payment page and the system log shows the follow: 

````
Error: SSL connect error, #0 /.../www/protected/extensions/paypalrestsdk/vendor/paypal/rest-api-sdk-p
hp/lib/PayPal/Auth/OAuthTokenCredential.php(243): PayPal\Core\PayPalHttpConnection->execute('grant_type=clie...')
#1
````

I'm using PayPal-PHP-SDK v1.3.0, suppose the Poodle issue is resolved and Payment API version is latest. 

I've tried to run curl command directly at server:
````
curl -sslv1 https://api.paypal.com
* About to connect() to api.paypal.com port 443 (#0)
*   Trying 173.0.88.98... connected
* Connected to api.paypal.com (173.0.88.98) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS: client certificate not found (nickname not specified)
* SSL connection using SSL_RSA_WITH_RC4_128_SHA
* Server certificate:
*       subject: CN=api.paypal.com,OU=PayPal Production,O="PayPal, Inc.",L=San Jose,ST=California,C=US
*       start date: Jul 03 00:00:00 2013 GMT
*       expire date: Jul 04 23:59:59 2015 GMT
*       common name: api.paypal.com
*       issuer: CN=VeriSign Class 3 Secure Server CA - G3,OU=Terms of use at https://www.verisign.com/rpa (c)10,OU=VeriSign Trust Network,O="VeriSign, Inc.",C=US
> GET / HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: api.paypal.com
> Accept: */*
> 
````

I've totally no clue on this, any comment will help! Thanks!

**Comment by jaypatel512** [comment]
Hey @judychu ! 

As you mentioned, you are seeing this issue intermittently. To resolve such issue, it is tricky to find the root cause. If possible, can you please [follow these instructions to setup samples](https://github.com/paypal/PayPal-PHP-SDK/wiki/Samples) in your local machine, or hosted machine, and see if you could reproduce that issue in samples ? 

The reason why I am asking that is, because the [samples](http://paypal.github.io/PayPal-PHP-SDK/sample/) are one source of truth for both of us, as they are functioning properly in many environments. If the issue exists in samples, we would know that there may be a potential issue in system settings, or firewall, or similar, and could find solution quicker.

Just follow the instructions to run samples here, and let me know if it fails.

**Comment by jaypatel512** [comment]
Any updates @judychu !

**Comment by judychu** [comment]
@jaypatel512 thanks so much for your reply!
Agree the issue happen intermittently which means almost not able to confirm the root cause...and like you said, sample running normal at my server. Actually we didn't encounter the SSL error account when the server traffic back to steady, without any code changes, that make me a stronger feel that huge amount of attempt would lead the problem. 

However, this is just my wild guess without any prove, believe I had to close the issue here first. Many thanks again for your reply!
