### ISSUE TITLE
api username/password/signature

### ISSUE THREAD

**Issue by michabbb** [paypal/PayPal-PHP-SDK#291]
is there a way to use

- api username
- api password
- api signature

instead of client-id and client secret ???

**Comment by jziaja** [comment]
Hi @michabbb , those credentials are used in context of PayPal's [Classic APIs](https://developer.paypal.com/docs/classic/).  This SDK is built around PayPal's newer [REST APIs](https://developer.paypal.com/docs/api/), which only use a configured REST application's client ID & client secret.

In order to use an API username, password, and signature, you'll need to use one of the older, Classic PHP SDKs based on what you're needing:
* [merchant-sdk-php](https://github.com/paypal/merchant-sdk-php)
* [adaptivepayments-sdk-php](https://github.com/paypal/adaptivepayments-sdk-php)
* [adaptiveaccounts-sdk-php](https://github.com/paypal/adaptiveaccounts-sdk-php)
* [permissions-sdk-php](https://github.com/paypal/permissions-sdk-php)
* [invoice-sdk-php](https://github.com/paypal/invoice-sdk-php)
* [buttonmanager-sdk-php](https://github.com/paypal/buttonmanager-sdk-php)
