### ISSUE TITLE
How to do Express Checkouts with Paypal SDK

### ISSUE THREAD

**Issue by steelbrain** [paypal/PayPal-PHP-SDK#373]
I want to achieve a checkout process like shown in the image below, I digged through the Paypal Dev docs as well as SDK docs, the closest thing I found it [in context checkouts][1] which are a different thing.
![11855461_1013790541988166_2046155671_n](https://cloud.githubusercontent.com/assets/4278113/9156601/2236f206-3e9d-11e5-80ea-d6f7801000b3.jpg)

[1]:https://developer.paypal.com/docs/classic/express-checkout/in-context/

**Comment by juwlee** [comment]
Hi @steelbrain [PayPal MTS](https://www.paypal.com/mts) should be able to help you with this. Please reach out to them.

**Comment by jaypatel512** [comment]
Do you mean this: http://paypal.github.io/PayPal-PHP-SDK/sample/#0adf233ad486604d0b6df90c586fbdad ?

**Comment by steelbrain** [comment]
@jaypatel512 I don't think that `#` matches something on that page :sweat_smile:

**Comment by jaypatel512** [comment]
Look for the first sample there, with text "PayPal Payments - similar to Express Checkout in Classic APIs"

**Comment by steelbrain** [comment]
@jaypatel512 I am already using that, but the page it produces is like a traditional payment page, unlike that shiny page I've posted image of, above.
![screen shot 2015-08-10 at 12 00 03](https://cloud.githubusercontent.com/assets/4278113/9179085/61b401a2-3f57-11e5-927e-a9863a70bddb.png)

**Comment by jaypatel512** [comment]
That is something that is not enforcable right now. You could also get a new UI randomly. This is a part of introducing the new UI in steps instead of moving the entire traffic. You should be able to see the new UI too.

This is one of my unofficial feedback: Try creating a new app in your sandbox, and try using that. See if that increases the chance of you getting UI for default. Again, this suggestion is not official. It may or may not work.

**Comment by steelbrain** [comment]
Great Thanks :rose:
