### ISSUE TITLE
sandbox working but live not. 401 error

### ISSUE THREAD

**Issue by kyegeorge** [paypal/PayPal-PHP-SDK#387]
I've ensured the client id & client secret is correct and created several different apps. All work perfectly with sandbox api but fail to connect when i switch to live. (bootsrap file modified, changed mode to live in sdk_config file and changed service endpoint to api.paypal.com, i still get the same 401 error

```php
$paypal = new \PayPal\Rest\ApiContext(
    new \PayPal\Auth\OAuthTokenCredential(
        '$liveClientID',   
        '$liveSecret'  )
);
```

**Comment by jaypatel512** [comment]
You do not need to change the service endpoint manually. You could just use `mode` flag to set it up. I am sure you have already followed the steps shown [here](https://github.com/paypal/PayPal-PHP-SDK/wiki/Going-Live). 

If it still fails, I think the issue seems to be in your account then, which [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) could help you fix that.

**Comment by kyegeorge** [comment]
that worked, thanks.

**Comment by jaypatel512** [comment]
Great. :+1: !! Happy coding.

**Comment by imchaitanyadesai** [comment]
I got 401 error on live. I am able to create card token but when i try to execute the payment. It show me message like unauthorized payment. Working fine on sandbox.

Is it something to do with future payment API. Because in sandbox all API permission is enable. while in live future payment and payout not.

**Comment by xiaoleih41** [comment]
I believe future payment has been deprecated and no  more new application will be accepted or approved. Payout is an advanced feature too.  Sandbox will allow you to test any advanced features but when it comes to production, you will have to be vetted for certain feature. Please click the account on developer dashboard under payout to click the enable link and start the application process.

**Comment by imchaitanyadesai** [comment]
I think future payment is not deprecated. If it deprecated then When i create my new business account it should not show me to enable future payment api.

**Comment by xiaoleih41** [comment]
have them enable those feature and see if they can.
