### ISSUE TITLE
Webhooks not send anything

### ISSUE THREAD

**Issue by MGDSoft** [paypal/PayPal-PHP-SDK#406]
Hi!,
Webhook not send a completed sale
My webhook is configured for https://miguel.wolopay.com/shop/payment/ipn_static/shop.payment.paypal_ipn_pay_method/
with all events

And my code

```php
        $payer = new ApiPaypal\Payer();
        $payer->setPaymentMethod("paypal");
        $item = new ApiPaypal\Item();
            $item->setName('blabla')
                ->setCurrency('EUR')
                ->setQuantity(1)
                ->setPrice(36.03);

        $itemList->addItem($item);
        $amount = new ApiPaypal\Amount();
        $amount
            ->setCurrency($paymentDetails->getCurrency()->getId())
            ->setTotal($paymentDetails->getAmount())
        ;

        $transaction = new ApiPaypal\Transaction();
        $transaction
            ->setAmount($amount)
            ->setItemList($itemList)
            ->setInvoiceNumber($paymentProcess->getId())
            ->setNotifyUrl($paymentInteract->getUrlIpn()) // Not used by PAYPAL.....
        ;

        $redirectUrls = new ApiPaypal\RedirectUrls();
        $redirectUrls
            ->setReturnUrl($paymentInteract->getUrlOk())
            ->setCancelUrl($paymentInteract->getUrlKo())
        ;

        $payment = new ApiPaypal\Payment();
        $payment
            ->setIntent("sale")
            ->setPayer($payer)
            ->setRedirectUrls($redirectUrls)
            ->setTransactions(array($transaction))
        ;

        try {
            $payment->create($this->createApiContext());

        } catch (\Exception $ex) {
            throw $ex;
        }
        
       // redirect to $payment->getApprovalLink()
```

The code is OK but webhook never is called WHY :___

**Comment by jaypatel512** [comment]
Hey @MGDSoft !

I am sure you must have followed the instructions specified here. https://github.com/paypal/PayPal-PHP-SDK/wiki/Webhook-Validation

From the look of it, it seems like you have the basic boiler plate ready. To make sure you are receiving the webhook correctly or not, I would recommend you doing these steps:

1. Create a bin using https://requestb.in/ . This allows you to receive the request on that URL. Think of this as a tiny request inspector. Dont worry about the HTTPS certificate issue.
2. Copy the BIN URL, which would look similar to this: http://requestb.in/abcdefgh
3. Create a new webhook on the client app in developer account in PayPal, and make sure to select "PAYMENT_SALE_COMPLETED" event, and use the URL you received from the request bin. Use `https` instead of `http` in the URL.
4. Create a sample payment from the code you have above. make sure you are using the same clientId and secret where you created a payment. 
5. In few seconds, refresh the request bin inspector window, and you should be able to see a webhook received. If you receive that webhook, it would mean that paypal is successfully sending requests to all the webhooks. 
6. PayPal will also send a similar request to your other webhook that is configured to your server URL. This would help you eliminiate any technical issues easily.

**Comment by MGDSoft** [comment]
Thanks for your help @jaypatel512 

But I tried with https://requestb.in/rnac9ern in other webhook And the inspector are clear...
I verified my credentials (is right) and configuration webhook is correct but webhook never call.

I dont known what happened but yesterday I lost all day with this integration :___.

**Comment by jaypatel512** [comment]
If you are still not receiving the webhooks, it seems to be the issue with your account, and not your integration. I would recommend reaching out to [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) to check into your account.

**Comment by omarkilani** [comment]
I also don't receive webhooks (only tested in the sandbox so far).

**Comment by MGDSoft** [comment]
Its a rare payment flow. Because it needs, make a "execute" after user approve his payment. (In return url, http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/ExecutePayment.html)

**Comment by jaypatel512** [comment]
Webhooks would only be sent after the `execute` flow has been completed. @MGDSoft ! Can you confirm if you are still not receiving the webhooks ? 

If not, it seems to be the issue with your account. Please reach out to [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) in that case. 

However, if you are receiving the webhooks, but getting an `InvalidArgumentException` as described here in #412, you need to follow the work around till the final fix has been made.

**Comment by MGDSoft** [comment]
Now tts working. Thx @jaypatel512

**Comment by andrejs-uibo** [comment]
I have a similar issue. The difference is that I receive webhooks that are sent in normal transaction flow, after I execute a payment. I don't receive any webhooks using Webhook Simulator and pressing on Resend button for ones, that have been sent. I even tested on  https://requestb.in, but never got any webhooks delivered there.
