### ISSUE TITLE
Billing Agreement start_date not respected

### ISSUE THREAD

**Issue by rmatil** [paypal/PayPal-PHP-SDK#420]
Hi all,

I'm trying to set the `start_date` for a new billing agreement as following: 

```php

$now = new DateTime('now', new DateTimeZone('Europe/Zurich'));
$now->modify('+5 minutes');

$billingAgreement = new Agreement();
$billingAgreement
    ->setName('New billing agreement')
    ->setDescription('Some description...')
    ->setStartDate($now->format(DateTime::ISO8601))
;

```

Unfortunately, the `start_date` of the created and executed billing agreement always returns 
```json
"start_date": "2015-10-11T22:00:00Z"
```

Then, i noticed that the documentation uses a format somehow different as PHP returns using `DateTime::ISO8601`. Therefore, i also tried creating billing agreements using the following to set the `start_date` to exactly the same as in the examples:

```php
...
    ->setStartDate($now->format('Y-m-d') . 'T' . $now->format('H:i:s') . 'Z')  
...
```

Unfortunately, this did not work either. 
Could you give some hints?

Btw: How much in the future must the billing agreement be to get executed? I can't find anything in the docs related to this...

**Comment by viion** [comment]
I had a similiar issue, the way I got it working was to use:  ``` gmdate("Y-m-d\TH:i:s\Z", time()+60) ```

This works for my project and it starts in 1 minute.

**Comment by rmatil** [comment]
Hi @viion 

Thanks for your reply. I just tried your example. Sometimes, it seems working, sometimes not. The result was now the following:

```json
"start_date": "2015-10-12T22:00:00Z"
```

Is there any information about the timezone, in which these dates should be sent?

**Comment by viion** [comment]
I happen to wonder if ``` ->setStartDate($now->format(DateTime::ATOM)) ``` would work?

I suggest this as I found a reddit post, relating to docs: http://php.net/manual/en/class.datetime.php

``` Note: This format is not compatible with ISO-8601, but is left this way for backward compatibility reasons. Use DateTime::ATOM or DATE_ATOM for compatibility with ISO-8601 instead. ```

**Comment by rmatil** [comment]
Funny, read this article too in the last days... Also, in my test it returned the wrong result again...

**Comment by ppmtscory** [comment]
@rmatil were you able to get this to work with having the `start_date` be in the future by just a short period?  It would need to be in the future to allow enough time for it to be created and executed, as @viion stated.

**Comment by rmatil** [comment]
@ppmtscory Unfortunately not, i tried with having the start date beginning between 1 and 10 minutes in the future. 
Is there an official statement about which timezone should be used?

**Comment by ppmtscory** [comment]
It simply needs to be a minute in the future.  As for timezone, the time you'll enter is standard UTC time so that'll be checked against your system time when it's determined to be in the future or not.  For example, I'm located in UTC -5 right now and it's 9 AM Central time.  Therefore, when I set the `start_date` in my request, I need to put `2015-10-20T14:01:00Z`.  Because you enter it in UTC format, I need to add 5 hours to it to match up with my current system time.

**Comment by viion** [comment]
To make sure it is clear, I believe the main issue is the timestamp reported back does not match the one set, and even if it did based on timezone offset, the minutes/seconds are always 00:00.

This happens for me, it must work correctly on PayPals side as I've tried setting a timezone as "now" and it failed (saying it was in the past, 2-3 seconds "sometimes worked" so it correctly checks down to the minute, and 60 always worked and it shows active in Paypal.

But even when a time is set, the return from the billing agreement query is not correct to the minutes/hours that is set, even in my responses.

**Comment by rmatil** [comment]
@viion Exactly, thanks for clearing this out

**Comment by viion** [comment]
Here is a **Billing Agreement** response example, this is a 12 month cycle.

```
[next_billing_date] => 2016-10-13T10:00:00Z
[last_payment_date] => 2015-10-13T11:57:02Z
```

The time this was started/initialized would be: 11:57:02 but the next billing date states 10:00:00, and as the ``` start date ``` is wrong:

```
[start_date] => 2015-10-12T23:00:00Z
````

According to that time stamp it should go active at 11 pm the day before it was initialized? Regardless of the hour, the minutes/seconds are ```00:00```,  they should have been ``` 57:02 ```.

Paypal showed "Active" in the sandbox, so I was assuming everything was OK and since Payment was made I am able to ignore time constraints in my application, but this is still a confusing response.

I had a look into the PayPal SDK file to see if I could find anything there but it looks to just be routing the response from PayPal API right back, so this seems to be an issue on PayPals end and not a bug in the SDK?

**Comment by ppmtscory** [comment]
Ah - I get it now - my apologies for the misinterpretation.  So, PayPal really doesn't care about the minutes/seconds after the initial start_date and, even then, it's only used to validate that the start date is actually in the future.  Once everything get's going and is activated, then it really only looks at the "day" which is why the date shows started the previous night about midnight (basically to reflect that it was activated that day).  To address your next billing date, PayPal runs multiple batches throughout the day for these payments, so that's why there's no minutes/seconds for those as well.  We don't say that it will be charged at that exact time, just that it will be charged that 'day'.  

Does that clarify and answer your questions?

**Comment by viion** [comment]
Hi Cory,

That makes a lot of sense, it is a bit confusing when just going off the documentation. This thread will likely help others. In my use case it never became a detrimental issue as Payment is made on that first one so my system doesn't care for another 12 months and just does an check then to make sure it's status is still "Active". 

Unsure if @rmatil did have an issue with their application that required precision times.

As for the question
> How much in the future must the billing agreement be to get executed? I can't find anything in the docs related to this...

A solid answer is; just enough for your request to go through. **60 Seconds** is good, if your requests takes longer than that to redirect to Paypal then I think there are more concerning issues!

**Comment by ppmtscory** [comment]
Exactly.  For each of my tests, I simply set it for a minute ahead of the current time and I didn't have any issues.

@rmatil please let us know if you have any concerns that have not been addressed.  If all is well, then I'll go ahead and close this issue out.

Thank @viion for the assist here!

**Comment by rmatil** [comment]
@viion @ppmtscory  Thanks for the clarification!
This resolves all my concerns about this date.
