### ISSUE TITLE
Can't find Invoice on GetAll() but can find by Get()

### ISSUE THREAD

**Issue by petersontubini** [paypal/PayPal-PHP-SDK#428]
Hi,

I can find this invoice ID "INV2-77GV-U25S-H5HB-B7BE" by Get()

But can't find by GetAll().

PS: This invoice was made by Paypal Here.

Is possible that I can create a filter just to retrieve all invoices (including Paypal Here?)

and why this invoice isn't appearing on getAll() ? Is this a bug?

**Comment by jaypatel512** [comment]
Just to confirm, do you follow the pagination on the `GetAll()` results ? It could be that it is not the first 20 results.

**Comment by petersontubini** [comment]
Yes, using the pagination

Enviado pelo meu Windows Phone
________________________________
De: Jay<mailto:notifications@github.com>
Enviada em: ‎02/‎11/‎2015 15:46
Para: paypal/PayPal-PHP-SDK<mailto:PayPal-PHP-SDK@noreply.github.com>
Cc: petersontubini<mailto:petersontubini@live.com>
Assunto: Re: [PayPal-PHP-SDK] Can't find Invoice on GetAll() but can find by Get() (#428)

Just to confirm, do you follow the pagination on the `GetAll()` results ? It could be that it is not the first 20 results.

---

**Comment by ppmtscory** [comment]
I'm going to close this out as it doesn't pertain specifically to the SDK.  The Get All was meant for use with Invoices that were created via the REST API Invoicing service.  If you'd like to file a formal feature request, please do so with a ticket to our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team so that it can be tracked accordingly with our internal teams.
