### ISSUE TITLE
Load Invoice Payer View Url

### ISSUE THREAD

**Issue by tomshaw** [paypal/PayPal-PHP-SDK#432]
When using loadInvoice() The payer_view_url property is no longer present. 

<pre>
["metadata"] => object(PayPal\Api\Metadata)#503 (1) {
      ["_propMap":"PayPal\Common\PayPalModel":private] => array(1) {
        ["created_date"] => string(23) "2015-11-03 12:48:33 PST"
      }
    }
</pre>

**Comment by ppmtscory** [comment]
@tomshaw can you let me know a version that this field was present?  I'd like to pinpoint where things changed.

**Comment by tomshaw** [comment]
@ppmtscory It's always been available as far as I know. According to a client within the last week it stopped working.

**Comment by ppmtscory** [comment]
I don't see that specific parameter listed in our documentation so that's the reason I asked.  I'll reach out to the Invoicing engineers to get more information and report back here afterwards.

**Comment by tomshaw** [comment]
Solved. After creating an invoice you have to send it at least once before Invoice::get payer_view_url property is available.

**Comment by ppmtscory** [comment]
@tomshaw you beat me to it!  That's the exact answer that I was going to give - I didn't realize initially that it was dependent on the Invoice status.  Thanks for updating!

**Comment by ldbglobe** [comment]
Unfortunately this issue is not solved ... 

I implemented few month ago an integrated invoice manager based on Paypal services and even after paiement, the payer_view_url was available and I used this to allow user to easily access to any payed invoice detail.

But for some unknown reason this information is no more present if the invoice is not in SENT status.

This is a real behaviour change and in my case induce a functionnality regression for my client

**Comment by ppmtscory** [comment]
The invoicing team is adding this field to additional statuses in the future.  I don't have any ETA to share for that other than they are hoping for early 2016.
