### ISSUE TITLE
Setup fee is becoming Zero and Status is pending

### ISSUE THREAD

**Issue by rahulrad7** [paypal/PayPal-PHP-SDK#451]
Created a plan with setup fee of USD 0.01, after bill agreement execution, I used below function to get agreement details. On that object setup fee value is 0.00. Also the state of agreement is Pending after execution also.

Agreement::get($id, $apiContext);

Please help me if I miss something for this issue.

**Comment by jan1206** [comment]
I'm seeing the same issue with the setup fee showing up as 0.00 when queried through the agreement (even though the plan was created with a setup fee). This is coming directly via JSON, so not an issue with the PHP SDK.

In my experience it can take the sandbox environment a minute or longer to execute the payment. Not sure how quick the response is on the live site. 

You can query the agreement after waiting for some time and it should be active. In which case you will see a transaction corresponding to the setup fee.

**Comment by ppmtscory** [comment]
@jan1206 is correct.  You aren't seeing the setup fee since the agreement is pending.  Once it's active, and the payment was charged, then you'll see it in the response.  Please file a support ticket with our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team to find out why your agreements are pending.  In your ticket, please include the account being used and also the agreement ID so that they can look it up to see the pending reason.
