### ISSUE TITLE
Operation timed out

### ISSUE THREAD

**Issue by artisangang** [paypal/PayPal-PHP-SDK#519]
It works fine with CC number 4148529247832259. But when i use 4111111111111111, It says Operation timed out after X milliseconds with 0 bytes received. 

![paypal](https://cloud.githubusercontent.com/assets/10267256/13660965/b1004266-e6b4-11e5-8cfe-092dc8f4b473.png)

**Comment by pp-randy** [comment]
@artisangang Thank you for reporting the issue.  I will follow up on that card number causing problems in the sandbox.

**Comment by pp-randy** [comment]
Internal Tracking ID: PPPLPAYPT-7022

**Comment by ppmtscory** [comment]
@artisangang I will be closing this issue as it doesn't have to do with the SDK itself.  This is due to the specific testing card number being overused in the system causing a timeout.  @pp-randy has already filed the internal ticket to do a DB update to try and correct this for the sandbox environment but it's not something that will likely get very high priority.  If you need test credit cards, please visit this [page](https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1413&expand=true&locale=en_US) and utilize Step 4.
