### ISSUE TITLE
Suddenly getting timed out error

### ISSUE THREAD

**Issue by guillermog** [paypal/PayPal-PHP-SDK#528]
Hi, we are suddenly experiencing a weird "Exception: Operation timed out after 0 milliseconds with 0 out of 0 bytes received" error when redirecting people from our custom checkout to paypal's payment page. It  seems to have started on Friday afternoon and it doesnt seem to be all of the time, sometimes people do get redirected correctly to paypal. Any ideas?

**Comment by ahfeel** [comment]
We are experiencing the same issue... Very very annoying..

Jérémie BORDIER

**Comment by ahfeel** [comment]
@guillermog Do you have any news about this issue ? It's getting really really annoying :(

**Comment by bluk** [comment]
Is there a PayPal-Debug-ID in the logs associated with these requests? Also, is there a specific PHP function call that you're making where the exception occurs?

**Comment by bluk** [comment]
Do you have any more specific timeframe when these issues occurred? Also, are they occurring for every request or only some? One other thing is to see if there are any other calls that failed (e.g. if you're making too many SDK calls at once, you may be rate limited; unlikely I hope but don't have much else to go on at the moment).

**Comment by ahfeel** [comment]
It's been happening every now and then since last friday evening. I have lots of timestamps of failed attempts, but nothing really helping I think.. I also have some RaaS API calls failing with the exact same timeout but I don't think it's related to any rate limit, it really looks way more like hitting a dead server in a round robin.

**Comment by guillermog** [comment]
@ahfeel sorry for the late reply but we've been running around trying to find a solution to this issue on our site. It seems to be happening less during the day now and more towards the afternoon and night, but we still get some failed attempts. We've decided to go with a different payment processor for now since we've had other similar issues with paypal in the past and we cant afford to spend anymore time trying to fix this issue for now. I will try to post back if we do find something.

**Comment by bluk** [comment]
If you're still encountering production issues, please contact [Merchant Technical Support](https://www.paypal-techsupport.com). They're your best bet to get this resolved since you can give them your account number/email with timestamps to look into the issue. Unfortunately without a debug ID, there are limits on what the SDK team can do to help you. Hope that helps.
