### ISSUE TITLE
can we ensure a payment is payed after call the execute payment api successfully?

### ISSUE THREAD

**Issue by flex1988** [paypal/PayPal-PHP-SDK#537]

**Comment by Caffe1neAdd1ct** [comment]
Have a look at `getPaymentSaleState()`
``` php
/**
     * Constants for comparsions are on this class
     * @return string ["completed", "partially_refunded", "pending", "refunded"]
     */
```

Check for "completed" should work..

**Comment by SDPrio** [comment]
Question is, which of these stats can exist right after the payment was executed. `partially_refunded` and `refunded` does not make a lot of these in this context, does it?

I think only `completed` and `pending` are valid here. Pending is used, when the customer does not have enough money on his PP account hand has to transfer funds from his bank account first. You then use a Webhook to get informed once the payment is completed. However there is no update, if the payment is canceled, is it?

**Comment by Caffe1neAdd1ct** [comment]
I would assume only Pending and Completed are valid on the returned `Payment` object after the `->execute()` method has been called.

However the same object can be collected after execution so presumably instead of implementing two calls with different returns the getPaymentSaleState accounts for both return on execute and later collections of the `Payment`.

An `->isPaid()` method would be useful on the returned `Payment` object which would check for `"completed"`, this would presumably need to account for refunded or partially_refunded and completed as the only NOT_PAID value would be `pending`, if refunded or partially refunded then the initial payment has been done so isPaid would need to return `true`.

Something like the following on the `Payment` object would be a nice helper method:

``` php
public function isPaid() {
    $paidStates = ["completed", "partially_refunded", "refunded"];
    return (in_array($this->getPaymentSaleState(), $paidStates)) ? true : false;
}
```

* note:- not tested

**Comment by flex1988** [comment]
so the payment is paid if ->getPaymentSaleState() is not pending?
but how can i know the payment is paid rather than refunded?
If a user want to refund his payment ,is the premisson of merchant needed?

**Comment by Caffe1neAdd1ct** [comment]
For a forced refund i believe it would have to go through the dispute procedure and you would receive notifications.

Otherwise you would need to implement a refund button on your application to call the REST refund call. At which point your system can track it has been refunded.

Another way would be:
```php
public function notRefunded() {
    $paidStates = ["completed", "pending"];
    return (in_array($this->getPaymentSaleState(), $paidStates)) ? true : false;
}
```

So to check:

``` php
if($payment->isPaid() && $payment->notRefunded()) {
    $doStuff = true;
}
```

Obviously the above example would rely on the payment object having the two new methods. You could always wrap the payment method in an object of your own with these methods available.

**Comment by flex1988** [comment]
@Caffe1neAdd1ct  ok thank you
