### ISSUE TITLE
How Can I get the specific error?

### ISSUE THREAD

**Issue by krasho** [paypal/PayPal-PHP-SDK#548]
Hello. I am getting this error: "Credit card was refused ", but I want to know the specific error.

The response is:
'{"name":"CREDIT_CARD_REFUSED","message":"Credit card was refused","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#CREDIT_CARD_REFUSED","debug_id":"2fb6a1eca07a0"}'

But the response doesn't say the specific error. Can I use the value of debug_id for that?

Thanks

**Comment by ppmtscory** [comment]
Unfortunately you won't get anything more specific than that.  For security purposes, we don't return the specific response from the card issuer back through into the API error message.  You can display extra information to your consumers if you'd like to.  For example, instead of just saying their card was declined, you could say something to the effect of... 

```Your credit card was declined.  Please check to make sure that you entered the correct information in regards to address, expiration date, and CVV2.  This information should match exactly to what your card issuing bank has on file.  If all of the information is correct, then you'll need to contact your card issuer to see why the card was denied.```
