### ISSUE TITLE
TRIAL & REGULAR at the same time.

### ISSUE THREAD

**Issue by darrell-uk** [paypal/PayPal-PHP-SDK#643]
### Required Information

- PHP Version: 5.6.25_1
- PayPal-PHP-SDK Version: 1.7.4
- Debug ID(s): 

### Issue Description

How do you set a TRIAL (one-off payment at sign-up) and a REGULAR payment at the same time? This does not work at it is below...

```
// # Payment definitions for this billing plan.
$paymentDefinition = new PaymentDefinition();
$paymentDefinition->setName('One-off Trial Payment')
    ->setType('TRIAL')
    ->setFrequency('Day')
    ->setFrequencyInterval("1")
    ->setCycles("1")
    ->setAmount(new Currency(array('value' => 10, 'currency' => 'USD')));
$paymentDefinition->setName('Regular Payments')
    ->setType('REGULAR')
    ->setFrequency('Month')
    ->setFrequencyInterval("2")
    ->setCycles("12")
    ->setAmount(new Currency(array('value' => 100, 'currency' => 'USD')));
//
```

**Comment by bluk** [comment]
Sorry for the late response. Please ensure that you are using 2 different `PaymentDefinition` objects.

Something like:
```
$trialPaymentDefinition = new PaymentDefinition();
$trialPaymentDefinition->setName('One-off Trial Payment')
    ->setType('TRIAL')
    ->setFrequency('Day')
    ->setFrequencyInterval("1")
    ->setCycles("1")
    ->setAmount(new Currency(array('value' => 10, 'currency' => 'USD')));
$regularPaymentDefinition = new PaymentDefinition();
$regularPaymentDefinition->setName('Regular Payments')
    ->setType('REGULAR')
    ->setFrequency('Month')
    ->setFrequencyInterval("2")
    ->setCycles("12")
    ->setAmount(new Currency(array('value' => 100, 'currency' => 'USD')));
```

And add both payment definitions to your billing plan. If there is still an issue, please leave a comment. Thanks!

**Comment by usamamashkoor** [comment]
Hi what if we want to give a user free 14 days trail after 14 days we want to charge them monthly $5 how we can set a free trail. ?

**Comment by pp-randy** [comment]
@usamamashkoor having two weeks as a $0 amount trial might work for you
```
"payment_definitions": [{
		"frequency_interval": 1,
		"amount": {
			"currency": "USD",
			"value": 0
		},
		"frequency": "Week",
		"cycles": 2,
		"type": "TRIAL",
		"name": "Two Weeks Free"
	}, {
		"frequency_interval": 1,
		"amount": {
			"currency": "USD",
			"value": 5.00
		},
		"frequency": "MONTH",
		"type": "REGULAR",
		"name": "Monthly Payment"
	}
]
```

**Comment by usamamashkoor** [comment]
Hi @pp-randy Thanks for the reply i have set the payment definition according to yours provided code in our paypal sandbox area in the payment details it shows this 
Trial Period Section.
Total cycles : 2
Remaining cycles : 2
Cycle frequency : Weekly 

if this is correct.. ? 

@pp-randy i have one more question related to testing the paypal trial subscription let say if the user is subscribed to our free trail and after 14 days our free trail ends and he does not have balance or pay for our paypal $5/month subscription then how we will test this scenario in our application because if he failed to pay for the $5 monthly subscription after the free trail then we will have to cancel his subscription in our paypal and also in our application to kindly let me know how i can verify this and solve it.  
Thanks again..

**Comment by pp-randy** [comment]
@usamamashkoor can you create a new issue and I can respond to you in it?  I have responded to other issues you have comments in, and I think its best to consolidate your questions into a single issue.

**Comment by usamamashkoor** [comment]
Thanks i will ask it in other issue which i have opened #1032 .
