### ISSUE TITLE
Direct Card Payments not executing in v1.10.0

### ISSUE THREAD

**Issue by paultarr** [paypal/PayPal-PHP-SDK#709]
### Required Information

- PHP Version: 5.4
- PayPal-PHP-SDK Version: 1.10
- Debug ID(s):

### Issue Description
Up until v1.8 the payment flow as described in https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/CreatePayment.php also executes a payment and responds with 'approved' or 'error'. 

From v1.10 we now receive 'created' as a response, at least on the sandbox site. Can you please confirm whether this is intended and if so, what additional steps are required to execute a direct card payment in this new version?

**Comment by jaypatel512** [comment]
It should not be based on SDK versions. the response coming back is from the server. We should be getting the same response from both the cases. 

The only change we did recently was using `PaymentCard` instead of `CreditCard`. Can you please check if you are using `PaymentCard` for v1.10. `CreditCard` is getting deprecated, and moving forward you should be fine using `PaymentCard`. Please let us know if you are seeing the same issue using `PaymentCard` ?

**Comment by paultarr** [comment]
Migrating to PaymentCard appears to have solved this for direct card transactions.

One further issue, can you advise what has happened to the vaulting of PaymentCard's (previously a method (CreditCard)$card->create() existed, however PaymentCard does not have this method. The samples do not illustrate how this is done with the new types.

**Comment by paultarr** [comment]
Additionally, can you confirm how a PaymentCardToken is set on a fundingInstrument? I can only see CreditCardToken detailed in https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Api/FundingInstrument.php

**Comment by pp-randy** [comment]
Are you using /vault/credit-card to vault PaymentCard details?  If so, I think you would still treat it as CreditCardToken.

**Comment by jaypatel512** [comment]
Hey @paultarr !

We are moving all APIs to use payment-card instead of credit card object. The change is more affected to the SDK users, as it changes the object you are supposed to use. You can still however, vault a credit card object as you did before, and use the `credit_card_token_id` returned back as shown here: http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreatePaymentUsingSavedCard.html
