### ISSUE TITLE
No way of fetching all of the agreements

### ISSUE THREAD

**Issue by kerneldemon** [paypal/PayPal-PHP-SDK#748]
Judging from [the documentation](https://developer.paypal.com/docs/api/payments.billing-agreements) and [the following stack overflow question](http://stackoverflow.com/questions/32811426/how-to-list-agreement-for-a-plan-using-paypal-rest-api) there's currently no way of fetching existing billing agreements for the account.

## Our use-case
We have a number of old transactions that we wish to retrieve through [the billing agreement transaction endpoint](https://developer.paypal.com/docs/api/payments.billing-agreements#agreement_transactions) after we fetch all of the agreements.

**Comment by bluk** [comment]
I believe this is a duplicate of https://github.com/paypal/PayPal-Python-SDK/issues/70 so will close this. The internal tracking is PPPLMER-11399.

You may also consider contacting [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/app/ask) so that they can log your request and associate it with a specific merchant account.
