### ISSUE TITLE
FAILED TO REFUND - RefundCapture.php

### ISSUE THREAD

**Issue by saber666** [paypal/PayPal-PHP-SDK#810]
### General information

* SDK/Library version: <Latest>
* Environment: Sandbox
* `PayPal-Debug-ID` values: d686725d6ffd2
* Language, language version, and OS: PHP

### Issue description

Used sample class RefundCapture.php from the SDK. Tried to refund a captured payment but when this line executes "$captureRefund = $capture->refundCapturedPayment($refundRequest, $apiContext);" I get this response: 

"FAILED TO REFUND{"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST","debug_id":"d686725d6ffd2"}"

Capture exists and $refundRequest is valid. Not sure why this is being returned. Any help would be appreciated.

Thanks - Mike

**Comment by pp-randy** [comment]
From the logs it appears this could be caused by the amount.  

https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/RefundCapture.php#L17-L18

What are you passing in for amount?  

Them sample creates it here: https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/AuthorizationCapture.php#L21-L23

**Comment by saber666** [comment]
Hi Randy,

I was passing an amount instead of an amount object. Seems to be working
now.

Thanks!

Mike

**Comment by pp-randy** [comment]
I'm glad you were able to resolve the issue.  

I submitted a request to improve the error messaging here: https://github.com/paypal/PayPal-REST-API-issues/issues/55
