### ISSUE TITLE
How do I reactivate DELETED plans?

### ISSUE THREAD

**Issue by ArcticZero** [paypal/PayPal-PHP-SDK#819]
I accidentally deleted an ACTIVE plan by using $plan->delete(), since I thought I was on Sandbox but apparently was not. There are currently users subscribed to this plan, so I'm wondering if there's some way I can somehow reactivate it.

Unfortunately I can't even seem to retrieve any DELETED plans, so in turn I can't use a patch to sort them out. Is there any solution to this?

Thanks.

**Comment by pp-randy** [comment]
Reach out to PayPal Technical Support they might be able to help restore it https://www.paypal-techsupport.com/app/ask/

I don't think this would directly impact the billing agreements though since I believe the plan details are used when creating the agreement but not much after that.   

If the support team cannot restore it then get details from an agreement that was created on the plan and create a new one. 

The deleted plans issue is being tracked here: https://github.com/paypal/PayPal-REST-API-issues/issues/28

**Comment by pp-randy** [comment]
Closing this issue, but let me know if you need further assistance.

**Comment by ArcticZero** [comment]
Glad to hear it does not affect existing billing agreements. I ended up just creating identical billing plans for future agreements. Will keep track of the issue as well.

Thank you for the response!
