### ISSUE TITLE
timeout errors

### ISSUE THREAD

**Issue by 54853315** [paypal/PayPal-PHP-SDK#870]
I integrated the PayPal SDK into my Laravel 5 app. Everything is up to date but suddenly sometimes I am getting the following error while creating a payment:
http://i.stack.imgur.com/NleDc.png
This error also not occures every time. So I don't know even where to start searching for an solution. My research at the www did not help my further yet. So I hope you guys can help me.

**Comment by xiaoleih41** [comment]
Is this in production environment or sandbox environment? It can be caused by multiple issues. Please take a look at [this article](https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1403&expand=true&locale=en_US) for possible cause Without a debug_Id, it will be hard for us to do research.  Please also search **timeout** or **operation timeout** within this **repository** and look for solved issues. If it doesn't help you, please contact [PayPal merchant technical support](https://www.paypal-techsupport.com/) on this.

**Comment by 54853315** [comment]
泥煤，都是中国人吧~那我就打中文了，我英文很烂。
我找到解决方法了，经过不断查看代码和调试代码，发现原来的是没用的。

每个需要调用curl的地方，都在执行一个代码：$httpConfig = new PayPalHttpConfig(null, 'POST', $config);

在PayPalHttpConfig里面的构造方法里，调用了一个自身方法getHttpConstantsFromConfigs()，在这里面，但凡外部传递的数组里是'http'打头的，就将可以替换PayPalHttpConfig的$defaultCurlOptions里的内容。
所以外部应该这样写：
$apiContext->setConfig(
            array(
                'log.LogEnabled' => true,
                'log.FileName' => 'PayPal-' . date('Y-m-d') . '.log',
                'log.LogLevel' => 'DEBUG',
                'http.CURLOPT_TIMEOUT' => 0,    //经测试,这才是有效让CURL的超时时间为0的写法
            )
        );

主要是这个 ： 'http.CURLOPT_TIMEOUT' => 0,    //经测试,这才是有效让CURL的超时时间为0的写法

**Comment by xiaoleih41** [comment]
That's good. You are right: `'http.CURLOPT_TIMEOUT' => 0` is the recommended way. Please check [here](https://github.com/paypal/PayPal-PHP-SDK/wiki/Curl-Options)
