### ISSUE TITLE
How to pass AccessToken / RefreshToken to ApiContext?

### ISSUE THREAD

**Issue by creifferscheid** [paypal/PayPal-PHP-SDK#929]
Hey guys,

I don't get the SDK. I get an auth_code and get my Refresh and AccessToken. I store the refreshToken, the accessToken and the expiryDate in my database.

The next time, I wan't to call the API, I wan't to pass the AccessToken to the $ApiContext, however there is no way to pass it?!

How do you do that? There is also no way to pass the refreshToken to the credentials or the apiContext. Why is that? This isn't covered in the samples either.

Can someone please post an example / sample on how to make an API Call using the REST API and this SDK with a valid AccessToken on behalf of an external paypal user?

Thanks and best!

**Comment by xiaoleih41** [comment]
I am not sure what exact usecase you are having but [here](https://github.com/paypal/PayPal-PHP-SDK/blob/master/sample/payments/CreateFuturePayment.php#L70) is a the sample case in future payment. Please refer to issue https://github.com/paypal/PayPal-PHP-SDK/issues/441 which may help with your case.

**Comment by theburhan** [comment]
I have the same problem. I would like to setup merchant onboarding, so that merchant does not have to enter client/secret id manually as there are chances of err and it can be that a backoffice user is non technical and would like to connect backoffice with PayPal. What my use case is. That I want to call create/update and execute actions of Payment object without even the use of ApiContext which requires vlient/secret id. It would be sufficient to use only access_token. 
Please advise some solution. Or refer to some documentation.

**Comment by xiaoleih41** [comment]
PayPal REST doesn't support the exact feature you are describing. However with the new payee email, you can facilitate payments to a 3rd party account instead of yours.  So you don't have to use the 3rd party's  API credentials. The API documents is [here] (https://developer.paypal.com/docs/api/payments/#definition-payee)

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been provided.
