### ISSUE TITLE
Connections fail on Mac due to SSL options

### ISSUE THREAD

**Issue by tempelmann** [paypal/PayPal-PHP-SDK#943]
Using 1.12.0, with sample folder from today's github repo (as it's missing from the normal download, even when downloading a fresh zip from the master repo, oddly).

I was wondering, why first.php didn't show any results. Turns out I get the dreaded "SSL peer handshake failed" error, see also #897.

First I tried to uncomment the line

    PayPalHttpConfig::$defaultCurlOptions[CURLOPT_SSLVERSION] = CURL_SSLVERSION_TLSv1_2;

inside sample/bootstrap.php - but that leads to another error:

/payments/CreatePaymentUsingPayPal.php - Class 'PayPalHttpConfig' not found in ... on line 41.

So I instead went into PayPalHttpConfig.php and removed all the SSL related lines following this line (21):

    public static $defaultCurlOptions = array(

Turns out the default SSL settings work just fine on a Mac, it seems. Now the code finally works.

**Comment by xiaoleih41** [comment]
We are looking into this.

**Comment by OwenMelbz** [comment]
@xiaoleih41 is there any update on this?

Thanks

**Comment by xiaoleih41** [comment]
We are working on the fix at this time. I will update the issue once it's solved.

**Comment by bluk** [comment]
The samples are not included when using `composer` or the GitHub zip to prevent issues where the samples may be exposed in a deployment and to reduce deployment sizes. We will make changes to the documentation and wiki to better highlight this change.

I updated the line for 
```
PayPalHttpConfig::$defaultCurlOptions[CURLOPT_SSLVERSION] = CURL_SSLVERSION_TLSv1_2;
```
 to
```
\PayPal\Core\PayPalHttpConfig::$defaultCurlOptions[CURLOPT_SSLVERSION] = CURL_SSLVERSION_TLSv1_2;
```
because I believe the error you encountered was due to it not being declared with the full namespace.

It is expected that some deployments will require changes to the [`$defaultCurlOptions`](https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Core/PayPalHttpConfig.php#L21) by setting this value in their codebase. Due to the various combinations of OpenSSL, curl, and PHP, different environments will require different values. Changing the default value now would cause backwards incompatibility issues. We will definitely consider this value in the next major SDK revision and will update our documentation to be clearer in the meantime.
