### ISSUE TITLE
Vault Card Documentation Deleted

### ISSUE THREAD

**Issue by Samistine** [paypal/PayPal-PHP-SDK#967]
Why?

I have customers using this.

**Comment by pp-randy** [comment]
Direct credit card processing with the Payments API was restricted for new integrations, please see the disclaimer in the [Payments API documentation](https://developer.paypal.com/docs/api/payments/).  It was causing additional confusion for new integrations to have the Vault API documented since it was primarily used with direct credit card processing.

For new integrations that require direct credit card processing we advise using [Braintree Direct](https://www.braintreepayments.com/products/braintree-direct).
