### ISSUE TITLE
No way to replace PayPalLoggingManager with a custom logging manager

### ISSUE THREAD

**Issue by hung5s** [paypal/PayPal-PHP-SDK#995]
This class only log debug info if the system is using sandbox. The problem is that if I want to keep a log of all the calls to Paypal with request and response data, we can't do that. Only in debug() the logged message has $data.
This is true at least for the PaypalHttpConnection class.  Here is its __construct:

```
    public function __construct(PayPalHttpConfig $httpConfig, array $config)
    {
        if (!function_exists("curl_init")) {
            throw new PayPalConfigurationException("Curl module is not available on this system");
        }
        $this->httpConfig = $httpConfig;
        $this->logger = PayPalLoggingManager::getInstance(__CLASS__);
    }
```
This way makes the $logger always be managed by PaypalLoggingManager. I can't change it to a custom logging manager.

**Comment by jaypatel512** [comment]
Hey @hung5s !

Please take a look at [wiki](https://github.com/paypal/PayPal-PHP-SDK/wiki/Logging) page about Logging in PayPal SDK. We do not expose request and response information on logs in live environment, because it can contain sensitive information, such as Credit Card number. You should be able to use your own custom logger by following the steps in that wiki page.
